### ISSUE TITLE
Bug: Lose filter on redirect

### ISSUE THREAD

**Issue by lumodon** [LearnersGuild/curriculum#87] opened 2017-07-11 16:30 UTC
### Summary
I partially lose my filter when navigating back to the curriculum page

### Steps to reproduce:
Go to https://curriculum.learnersguild.org/phases/3/skills
Click *Filters* and select *SQL*
Click on *Can build a SQL schema for a given problem definition* to navigate to a different page
Click the BACK button in your browser.
Notice that *SQL* is still typed in the filter, yet the list shows all articles.
Focus on the text input and press enter key to reactivate filter

### What I expected to happen instead:
Navigating to another page and then clicking back button should load the page with my filter still applied, OR: with my filter not applied but text input is empty.

**Comment by deadlyicon** [comment] 2017-09-21 19:01
duplicate of https://github.com/LearnersGuild/curriculum/issues/249

**Closed by deadlyicon** 2017-09-21 19:01 UTC
