### ISSUE TITLE
Skills checkboxes are not saving

### ISSUE THREAD

**Issue by kelceywilson** [LearnersGuild/curriculum#382] opened 2017-10-06 22:22 UTC
# Bug Report

I found a problem on https://curriculum.learnersguild.org/skills

Skills I've mastered and checked off don't stay checked off after refreshing or leaving and returning.

**Comment by jrpool** [comment] 2017-10-06 22:27
> I found a problem on https://curriculum.learnersguild.org/skills
> 
> Skills I've mastered and checked off don't stay checked off after refreshing or leaving and returning.

This is a known problem. Notices were sent on Slack to all learners in P1, P2, and P3 yesterday warning them of this problem and advising not to use this feature until the bug is repaired.

I made a repair yesterday, and it is now awaiting review and approval by an SEP.

When it has been incorporated into the running software, I intend to send out another notice reporting that the feature is usable again.

Sorry that we did not deal with it earlier, and please keep reporting bugs.

**Comment by judytuna** [comment] 2017-10-11 19:16
Thank you @kelceywilson for reporting and @jrpool for noticing ahead of time and fixing. I'm marking this as a duplicate of https://github.com/LearnersGuild/curriculum/pull/381 -- please follow along with progress there.

**Closed by judytuna** 2017-10-11 19:16 UTC
Labels: bug, duplicate, phase4
